// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwxdWFFAI8DucgLT72kcAPspI055ASzoU',
    appId: '1:463309330565:web:cde034c48ae7cbc8a871ec',
    messagingSenderId: '463309330565',
    projectId: 'flutter-maps-cbb54',
    authDomain: 'flutter-maps-cbb54.firebaseapp.com',
    storageBucket: 'flutter-maps-cbb54.appspot.com',
    measurementId: 'G-PLLH4K4P6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8IV1846q-pmFontW_dy3Pw_wjHci89v4',
    appId: '1:463309330565:android:c5fdee4031e7e96aa871ec',
    messagingSenderId: '463309330565',
    projectId: 'flutter-maps-cbb54',
    storageBucket: 'flutter-maps-cbb54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACnm28gCZieh40Bz4803S0G2I6RKxfEA4',
    appId: '1:463309330565:ios:3e8cd0ccfdff0c13a871ec',
    messagingSenderId: '463309330565',
    projectId: 'flutter-maps-cbb54',
    storageBucket: 'flutter-maps-cbb54.appspot.com',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACnm28gCZieh40Bz4803S0G2I6RKxfEA4',
    appId: '1:463309330565:ios:bd97492cf2fad345a871ec',
    messagingSenderId: '463309330565',
    projectId: 'flutter-maps-cbb54',
    storageBucket: 'flutter-maps-cbb54.appspot.com',
    iosBundleId: 'com.example.flutterMaps.RunnerTests',
  );
}
